const actionTypes = {
    "NEW_MOVE": "NEW_MOVE",
    "GENERATE_CANDIDATE_MOVES": "GENERATE_CANDIDATE_MOVES",
    "CLEAR_CANDIDATE_MOVES": "CLEAR_CANDIDATE_MOVES",
    "OPEN_PROMOTION": "OPEN_PROMOTION",
    "PROMOTION_CLOSE": "PROMOTION_CLOSE",
}

export default actionTypes;