const actionTypes = {
    "NEW_MOVE": "NEW_MOVE",
    "GENERATE_CANDIDATE_MOVES": "GENERATE_CANDIDATE_MOVES",
    "CLEAR_CANDIDATE_MOVES": "CLEAR_CANDIDATE_MOVES",
    "OPEN_PROMOTION": "OPEN_PROMOTION",
    "PROMOTION_CLOSE": "PROMOTION_CLOSE",
    "CAN_CASTLE": "CAN_CASTLE",
    "STALEMATE": "STALEMATE",
    "NEW_GAME": "NEW_GAME",
    "INSUFFICIENT_MATERIAL": "INSUFFICIENT_MATERIAL",
    "WIN" : "WIN",
}

export default actionTypes;